name: Python CI  

#Trigger the workflow on any push to the main branch or pull request
on: 
    push:   # An event fired when the pull request is pushed
        branches:
            - main 
    
    pull_request:
        branches:
            - main 

jobs: 
    
    # A job to build and test the Python code
    test:
        
        # The type of runner that the job will run on server as a container 
        runs-on: ubuntu-latest
        
        # These are the workflow Steps to perform the build and test
        steps:
        
        # Check out the repository 
        - name: Checkout repository
          uses: actions/checkout@v2
        
        # Set up Python environment
        - name: Set up Python environment
          uses: actions/setup-python@v2
          with:
            python-version: '3.11'
        
        # Install required dependencies 
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        # Run the tests
        - name: Run tests # Will find the test folder and run it
          run: pytest
        
        # Upload the test coverage report to Codecov
